# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'AwesomeProject2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeProject2
  pod ‘Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'



  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  target 'AwesomeProject2Tests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'AwesomeProject2-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AwesomeProject2-tvOS

  target 'AwesomeProject2-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
